### ISSUE TITLE
Unable to harvest Biomedcentral's OAI PMH feed

### ISSUE THREAD

**Issue by tpmccallum** [infrae/pyoai#14]
Hi,
I am able to harvest most repositories with this code. Works great, thank you!

I am however unable to harvest 

```
http://www.biomedcentral.com/oai/2.0/
```

This OAI PMH feed works in the browser but throws the following error when running the Python code from the README file, see error below. (My guess is biomedcentral provides more than the average site (list of DC in the browser seems really long) per resumption token and the code is timing out). Any assistance would be greatly appreciated.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyoai-2.4.4-py2.7.egg/oaipmh/common.py", line 115, in method
    return obj(self, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pyoai-2.4.4-py2.7.egg/oaipmh/common.py", line 110, in __call__
    return bound_self.handleVerb(self._verb, kw)
  File "/usr/local/lib/python2.7/dist-packages/pyoai-2.4.4-py2.7.egg/oaipmh/client.py", line 65, in handleVerb
    kw, self.makeRequestErrorHandling(verb=verb, **kw))    
  File "/usr/local/lib/python2.7/dist-packages/pyoai-2.4.4-py2.7.egg/oaipmh/client.py", line 269, in makeRequestErrorHandling
    xml = self.makeRequest(**kw)
  File "/usr/local/lib/python2.7/dist-packages/pyoai-2.4.4-py2.7.egg/oaipmh/client.py", line 316, in makeRequest
    return retrieveFromUrlWaiting(request)
  File "/usr/local/lib/python2.7/dist-packages/pyoai-2.4.4-py2.7.egg/oaipmh/client.py", line 362, in retrieveFromUrlWaiting
    raise Error, "Waited too often (more than %s times)" % wait_max
oaipmh.client.Error: Waited too often (more than 5 times)
```

**Comment by mpasternak** [comment]
Hi @tpmccallum I'm willing to assist you with this issue if it is still relevant to you. If so, please let me know, how are you harvesting this code, eg. post a minimal non-working code sample. We had a release recently so please make sure you test this with the most recent version available. Thanks!

**Comment by interrogator** [comment]
Stale, no response from user, vote to close

**Comment by tpmccallum** [comment]
Hi @mpasternak and @interrogator 
I no longer require this functionality. 
Thank you, this can be closed.
